name: Deploy to Minikube

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.27.0'

      - name: Apply Kubernetes Manifests
        run: |
          kubectl apply -f k8s/tomcat-deployment.yaml
          kubectl apply -f k8s/tomcat-service.yaml

